[package]
name = "christina-git"
version = "0.1.0"
description = "Git integration for Christina."
edition = "2024"

[dependencies]
christina-core = { path = "../christina-core" }
thiserror = { workspace = true }
git2 = { version = "0.20.3", default-features = false }

[dev-dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
