import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { suffix } from "bun:ffi";

/**
 * Compiles a standalone, single-file `charlotte` executable via
 * `bun build --compile`. The native crate has no cross-compilation setup,
 * so this only targets the host platform `cargo build --release` just
 * produced — not the full `bun-*` target matrix `bun build --compile`
 * supports for pure-JS CLIs.
 *
 * The native library is embedded into the executable rather than shipped
 * as a sidecar file: `packages/native-core/src/native-lib.generated.ts` is
 * temporarily overwritten with a `with { type: "file" }` import of the
 * compiled library (the one import shape Bun materializes to a real
 * on-disk path at runtime, which `bun:ffi`'s `dlopen` needs), then restored
 * to its checked-in placeholder afterward so `git status` stays clean.
 */
const repoRoot = path.resolve(import.meta.dir, "../../..");
const nativeCrateDir = path.join(repoRoot, "native/charlotte-core");
const distDir = path.join(repoRoot, "dist");
const generatedModulePath = path.join(
  repoRoot,
  "packages/native-core/src/native-lib.generated.ts"
);

const cargoBuild = Bun.spawnSync(
  [
    "cargo",
    "build",
    "--release",
    "--manifest-path",
    path.join(nativeCrateDir, "Cargo.toml"),
  ],
  { stderr: "inherit", stdout: "inherit" }
);
if (cargoBuild.exitCode !== 0) {
  process.exit(cargoBuild.exitCode ?? 1);
}

const libFileName =
  suffix === "dll" ? "charlotte_core.dll" : `libcharlotte_core.${suffix}`;
const libAbsPath = path.join(nativeCrateDir, "target/release", libFileName);
const importSpecifier = path
  .relative(path.dirname(generatedModulePath), libAbsPath)
  .split(path.sep)
  .join("/");

const placeholder = readFileSync(generatedModulePath, "utf-8");
writeFileSync(
  generatedModulePath,
  `// Generated by apps/cli/scripts/compile.ts — restored after compiling.\n` +
    `import path from ${JSON.stringify(importSpecifier)} with { type: "file" };\n` +
    "export default path;\n"
);

try {
  mkdirSync(distDir, { recursive: true });
  const outfile = path.join(
    distDir,
    process.platform === "win32" ? "charlotte.exe" : "charlotte"
  );
  const bunBuild = Bun.spawnSync(
    [
      "bun",
      "build",
      path.join(import.meta.dir, "../src/cli.ts"),
      "--compile",
      "--outfile",
      outfile,
    ],
    { stderr: "inherit", stdout: "inherit" }
  );
  if (bunBuild.exitCode !== 0) {
    process.exit(bunBuild.exitCode ?? 1);
  }
  console.log(`Compiled: ${outfile}`);
} finally {
  writeFileSync(generatedModulePath, placeholder);
}
