[package]
name = "christina-core"
version = "0.1.0"
description = "Core domain logic, types, and shared utilities for Christina."
edition = "2024"

[dependencies]
anyhow = { workspace = true }
compact_str = { workspace = true }
git2 = { workspace = true, optional = true }
keyring = { version = "3", optional = true }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[features]
default = ["keyring-support"]
git2-support = ["git2"]
keyring-support = ["keyring"]

[lints]
workspace = true
